
************************************************************
* LTPI(LTPI)
* Version 0.0
* (C)2021 Cue H. Lee
* Columbia University
* Unlicensed software
************************************************************
Call: 
./pleio.py \
--out /ifs/scratch/msph/eigen/hl3565/01_MTGB/codes/source/LTPI_package/test_imp \
--bin /ifs/scratch/msph/eigen/hl3565/01_MTGB/codes/source/LTPI_package/example/binput.txt \
--prevalence /ifs/scratch/msph/eigen/hl3565/01_MTGB/codes/source/LTPI_package/example/prevalence.txt \
--gencov /ifs/scratch/msph/eigen/hl3565/01_MTGB/codes/source/LTPI_package/example/genetic_covariance_bin.txt 

Beginning analysis at Thu Jan 18 14:54:44 2024
Prevalence file contains 3 traits
Traceback (most recent call last):
  File "/ifs/scratch/msph/eigen/hl3565/01_MTGB/codes/source/LTPI_package/LTPI.py", line 285, in <module>
    args.GENCOV = read_cov(args.gencov, args.binary_traits)
  File "/ifs/scratch/msph/eigen/hl3565/01_MTGB/codes/source/LTPI_package/LTPI.py", line 200, in read_cov
    cov_raw = pd.read_csv(f, sep='\t', header='infer', index_col=None)
  File "/ifs/scratch/msph/eigen/hl3565/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/ifs/scratch/msph/eigen/hl3565/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 468, in _read
    return parser.read(nrows)
  File "/ifs/scratch/msph/eigen/hl3565/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 1057, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/ifs/scratch/msph/eigen/hl3565/anaconda3/lib/python3.8/site-packages/pandas/io/parsers.py", line 2061, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 756, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 771, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 827, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1951, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 6, saw 2


Analysis finished at Thu Jan 18 14:54:44 2024
Total time elapsed: 
